= Radio-GPS PCB
The 2 Space Maniac boards, Murgas and Celeste will rest on the board, and the connectors of both boards will connect to that on the GPS-RadioPCB

Purpose for board: 
First reason is to achieve accurate time sync across the devices on satellite by using a low jitter Fanout Chip for the GPS PPS output.
Second reason is to receive the Radio and GPS outputs and link them to PC104 to the rest of satellite. this is required as the connector of both Space Maniac Modules are not directly compatible to PC104.

Molex SlimStack :
This is the connector used by both Space Maniac boards. Traces will be made to link its pins to that of PC104.

link:https://www.ti.com/product/LMK1C1104[LMK1C1104 Fanout Chip:]
This takes input of PPS signal from GPS and fanouts into 4 PPS lines with low jitter, which helps achieve high time accuracy across the devices, OBC, Payload Controller, ADCS and Radio. This prevents inconsistencies in task logging and command carrying out.

Outputs of Radio:
I2C, CAN.
EXT_RST, which resets GNSS Receiver.

Outputs of GNSS Receiver.:
PPS : 1 second time synchronisation signal.
I2C, CAN : sends timestamps in accordance to each PPS pulse.